# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='CarImgLikeViewTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(db_column='MEMBER_ID', max_length=255)),
                ('vh_img_id', models.CharField(db_column='VH_IMG_ID', max_length=20)),
                ('bool_like', models.IntegerField(blank=True, db_column='BOOL_LIKE', null=True)),
                ('hits', models.IntegerField(blank=True, db_column='HITS', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'CAR_IMG_LIKE_VIEW_TB',
            },
        ),
        migrations.CreateModel(
            name='CommonCodeTb',
            fields=[
                ('group_cd', models.CharField(blank=True, db_column='GROUP_CD', max_length=4, null=True)),
                ('group_cd_nm', models.CharField(blank=True, db_column='GROUP_CD_NM', max_length=20, null=True)),
                ('common_cd', models.CharField(db_column='COMMON_CD', max_length=4, primary_key=True, serialize=False)),
                ('common_cd_nm', models.CharField(blank=True, db_column='COMMON_CD_NM', max_length=20, null=True)),
                ('upper_common_cd', models.CharField(blank=True, db_column='UPPER_COMMON_CD', max_length=4, null=True)),
                ('upper_group_cd', models.CharField(blank=True, db_column='UPPER_GROUP_CD', max_length=4, null=True)),
                ('attribute', models.CharField(blank=True, db_column='ATTRIBUTE', max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, db_column='ORDER', null=True)),
                ('user', models.IntegerField(blank=True, db_column='USER', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'COMMON_CODE_TB',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='MemberTb',
            fields=[
                ('mem_id', models.CharField(db_column='MEM_ID', max_length=255, primary_key=True, serialize=False)),
                ('mem_userid', models.IntegerField(blank=True, db_column='MEM_USERID', null=True)),
                ('pw', models.CharField(blank=True, db_column='PW', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True)),
                ('sex', models.CharField(blank=True, db_column='SEX', max_length=4, null=True)),
                ('job', models.CharField(blank=True, db_column='JOB', max_length=255, null=True)),
                ('reg_date', models.DateField(blank=True, db_column='REG_DATE', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'MEMBER_TB',
            },
        ),
        migrations.CreateModel(
            name='VehicleDataTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_cd', models.CharField(db_column='MODEL_CD', max_length=4)),
                ('detail_model_cd', models.CharField(db_column='DETAIL_MODEL_CD', max_length=4)),
                ('vh_info_cd', models.CharField(db_column='VH_INFO_CD', max_length=4)),
                ('vh_info_value', models.CharField(blank=True, db_column='VH_INFO_VALUE', max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'VEHICLE_DATA_TB',
            },
        ),
        migrations.CreateModel(
            name='VehicleImgTb',
            fields=[
                ('vh_img_id', models.CharField(db_column='VH_IMG_ID', max_length=20, primary_key=True, serialize=False)),
                ('model_cd', models.CharField(blank=True, db_column='MODEL_CD', max_length=4, null=True)),
                ('color_cd', models.CharField(blank=True, db_column='COLOR_CD', max_length=4, null=True)),
                ('package_cd', models.CharField(blank=True, db_column='PACKAGE_CD', max_length=20, null=True)),
                ('angle_cd', models.CharField(blank=True, db_column='ANGLE_CD', max_length=20, null=True)),
                ('weather_cd', models.CharField(blank=True, db_column='WEATHER_CD', max_length=20, null=True)),
                ('date', models.DateField(blank=True, db_column='DATE', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_column='UPDATE_TIME', null=True)),
                ('use', models.IntegerField(blank=True, db_column='USE', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'VEHICLE_IMG_TB',
            },
        ),
    ]
